import type { Series } from "../entities/Series";
import autores from "./authors";

const series: Series[] = [
  {
    id: "harry-potter",
    title: "Harry Potter",
    description:
      "A série de books Harry Potter, escrita por J.K. Rowling, segue a jornada de um jovem bruxo, Harry Potter, enquanto ele descobre seu lugar no mundo mágico e enfrenta desafios para derrotar o malvado bruxo Lord Voldemort. Ao longo de sete books, Harry e seus amigos, Hermione Granger e Ron Weasley, exploram a magia, enfrentam perigos e aprendem sobre amizade, coragem e o poder da escolha em uma luta épica entre o bem e o mal.",
    author: autores[0],
    year: 1997,
    image:
      "https://ingresso-a.akamaihd.net/b2b/production/uploads/article/image/2549/7ababc2015043445b750ebc853a5f706.jpg",
    books: [
      {
        id: "harry-potter-e-a-pedra-filosofal",
        title: "Harry Potter e a Pedra Filosofal",
        author: autores[0],
        year: 1997,
        order: 1,
        image: "https://m.media-amazon.com/images/I/81pB+joKL4L._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96G4?ref_=dbs_p_pwh_rwt_anx_cl_0&storeType=ebooks",
      },
      {
        id: "harry-potter-e-a-camara-secreta",
        title: "Harry Potter e a Câmara Secreta",
        author: autores[0],
        year: 1998,
        order: 2,
        image: "https://m.media-amazon.com/images/I/81D+5aMHzFL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96K0?ref_=dbs_p_pwh_rwt_anx_cl_1&storeType=ebooks",
      },
      {
        id: "harry-potter-e-o-prisioneiro-de-azkaban",
        title: "Harry Potter e o Prisioneiro de Azkaban",
        author: autores[0],
        year: 1999,
        order: 3,
        image: "https://m.media-amazon.com/images/I/81Q+2zleuwL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96HI?ref_=dbs_p_pwh_rwt_anx_cl_2&storeType=ebooks",
      },
      {
        id: "harry-potter-e-o-calice-de-fogo",
        title: "Harry Potter e o Cálice de Fogo",
        author: autores[0],
        year: 2000,
        order: 4,
        image: "https://m.media-amazon.com/images/I/81IsnaNraBL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96FA?ref_=dbs_p_pwh_rwt_anx_cl_3&storeType=ebooks",
      },
      {
        id: "harry-potter-e-a-order-da-fenix",
        title: "Harry Potter e a order da Fênix",
        author: autores[0],
        year: 2003,
        order: 5,
        image: "https://m.media-amazon.com/images/I/81ZQUV67MGL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96IC?ref_=dbs_p_pwh_rwt_anx_cl_4&storeType=ebooks",
      },
      {
        id: "harry-potter-e-o-enigma-do-principe",
        title: "Harry Potter e o Enigma do Príncipe",
        author: autores[0],
        year: 2005,
        order: 6,
        image: "https://m.media-amazon.com/images/I/81SZC96OGOL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96LY?notRedirectToSDP=1&ref_=dbs_mng_calw_5&storeType=ebooks",
      },
      {
        id: "Harry Potter e as Reliquias da Morte",
        title: "Harry Potter e as Relíquias da Morte",
        author: autores[0],
        year: 2007,
        order: 7,
        image: "https://m.media-amazon.com/images/I/81PbdwXqKkL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96GE?notRedirectToSDP=1&ref_=dbs_mng_calw_6&storeType=ebooks",
      },
      {
        id: "harry-potter-e-a-crianca-amaldicoada",
        title: "Harry Potter e a Criança Amaldiçoada",
        author: autores[0],
        year: 2016,
        order: 8,
        image: "https://rocco.com.br/app/uploads/2024/04/9786555322682.jpg",
        link: "https://www.amazon.com.br/Harry-Potter-Crian%C3%A7a-Amaldi%C3%A7oada-Parte/dp/8532530435",
      },
    ],
  },
  {
    id: "o-senhor-dos-aneis",
    title: "O Senhor dos Anéis",
    description:
      "A trilogia O Senhor dos Anéis, escrita por J.R.R. Tolkien, narra a aventura épica de Frodo Bolseiro, um hobbit que recebe a missão de destruir o poderoso Anel do Poder e impedir que ele caia nas mãos do sombrio Senhor Sauron. Acompanhado por um grupo diverso de heróis, Frodo enfrenta batalhas, perigos sobrenaturais e tentações, em uma jornada que explora temas de coragem, sacrifício e amizade. A história celebra a luta do bem contra o mal em um vasto e detalhado mundo de fantasia, a Terra-média.",
    author: autores[1],
    year: 1954,
    image:
      "https://cinepop.com.br/wp-content/uploads/2021/12/o-senhor-dos-aneis.jpg",
    books: [
      {
        id: "a-sociedade-do-anel",
        title: "A Sociedade do Anel",
        author: autores[1],
        year: 1954,
        order: 1,
        image: "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3C98K98?ref_=dbs_p_pwh_rwt_cpsb_cl_0&storeType=ebooks",
      },
      {
        id: "as-duas-torres",
        title: "As Duas Torres",
        author: autores[1],
        year: 1954,
        order: 2,
        image: "https://m.media-amazon.com/images/I/81N9hxO6XdL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3CCH4XF?ref_=dbs_p_pwh_rwt_cpsb_cl_1&storeType=ebooks",
      },
      {
        id: "o-retorno-do-rei",
        title: "O Retorno do Rei",
        author: autores[1],
        year: 1955,
        order: 3,
        image: "https://m.media-amazon.com/images/I/81LUEEYfQNL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3D2GFXN?ref_=dbs_p_pwh_rwt_cpsb_cl_2&storeType=ebooks",
      },
    ],
  },
  {
    id: "as-cronicas-de-gelo-e-fogo",
    title: "As Crônicas de Gelo e Fogo",
    description:
      "As Crônicas de Gelo e Fogo, série escrita por George R.R. Martin, acompanha a luta pelo Trono de Ferro em Westeros, um continente marcado por rivalidades, alianças e traições. Nobres famílias, como os Starks, Lannisters e Targaryens, jogam um perigoso jogo de intrigas, onde poder e sobrevivência andam lado a lado. Enquanto reis e rainhas disputam o controle dos Sete Reinos, uma antiga ameaça cresce ao norte, e o inverno se aproxima, trazendo consigo o perigo dos Caminhantes Brancos. A série explora temas de poder, lealdade e moralidade em uma narrativa complexa e repleta de reviravoltas.",
    author: autores[2],
    year: 1996,
    image:
      "https://img.odcdn.com.br/wp-content/uploads/2024/07/Design-sem-nome-16-1-scaled.jpg",
    books: [
      {
        id: "a-guerra-dos-tronos",
        title: "A Guerra dos Tronos",
        author: autores[2],
        year: 1996,
        order: 1,
        image: "https://m.media-amazon.com/images/I/91eHityofNL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07PPB9QW1?ref_=dbs_p_pwh_rwt_anx_cl_0&storeType=ebooks",
      },
      {
        id: "a-furia-dos-reis",
        title: "A Fúria dos Reis",
        author: autores[2],
        year: 1998,
        order: 2,
        image: "https://m.media-amazon.com/images/I/91N6C0jwzuL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07QYPLKV1?ref_=dbs_p_pwh_rwt_anx_cl_1&storeType=ebooks",
      },
      {
        id: "a-tormenta-de-espadas",
        title: "A Tormenta de Espadas",
        author: autores[2],
        year: 2000,
        order: 3,
        image: "https://m.media-amazon.com/images/I/91VVZ-v5GYL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07QXSYDSB?ref_=dbs_p_pwh_rwt_anx_cl_2&storeType=ebooks",
      },
      {
        id: "o-festim-dos-corvos",
        title: "O Festim dos Corvos",
        author: autores[2],
        year: 2019,
        order: 4,
        image: "https://m.media-amazon.com/images/I/814UZhEYFfL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B081284MLJ?notRedirectToSDP=1&ref_=dbs_mng_calw_3&storeType=ebooks",
      },
      {
        id: "a-danca-dos-dragoes",
        title: "A Dança dos Dragões",
        author: autores[2],
        year: 2020,
        order: 5,
        image: "https://m.media-amazon.com/images/I/91DisjRjFxL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B084SS25D3?notRedirectToSDP=1&ref_=dbs_mng_calw_4&storeType=ebooks",
      },
    ],
  },
];

export default series;
